import { ApiError, authenticate, diagnoseAttempt } from "./api.js";
import { loadState, saveState, updateStage } from "./store.js";
import { type RescueState, type Stage } from "./types.js";

const root = document.querySelector<HTMLElement>("#app");
if (!root) throw new Error("App mount point is missing.");
const appRoot: HTMLElement = root;

let state = loadState();
let cameraStream: MediaStream | undefined;
let authMode: "signup" | "login" = "signup";
const stages: readonly Stage[] = ["analysing", "diagnosis", "lesson", "practice", "success", "progress"];
const escape = (value: string): string => value.replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char] ?? char));
const icon = (name: string): string => `<span class="material-symbols-outlined">${name}</span>`;

function nav(): string { return `<header class="top"><button class="link" data-action="home">${icon("arrow_back")} Back</button><strong class="brand">SabiCoach</strong>${state.authenticated ? `<button class="account" data-action="logout">${icon("account_circle")} ${escape(state.displayName)}</button>` : ""}</header>`; }
function stepper(): string { const active = Math.max(1, stages.indexOf(state.stage) + 1); return `<div class="stepper">${["Analyse", "Find the gap", "Repair", "Prove mastery", "Rescue Map"].map((label, index) => `<span class="${index < active ? "active" : ""}"><i>${index + 1}</i>${label}</span>`).join("")}</div>`; }

function home(): string { const gap = state.targetScore - state.currentScore; return `<main class="shell home"><p class="eyebrow">JAMB 2026 · Mathematics</p><h1>Every mistake has a way back.</h1><p class="lede">You are <b>${gap} marks</b> from your target. Scan a past question and SabiCoach will show you the shortest route to recover them.</p><section class="hero-card"><div><span class="eyebrow light">TODAY'S FASTEST WIN</span><h2>Fix sign-change errors</h2><p>Estimated marks to recover: <b>+${state.diagnosis.recoverableMarks}</b></p><div class="scores"><b>${state.currentScore}</b><span>→</span><b>${state.targetScore}</b></div><small>CURRENT MOCK &nbsp;&nbsp;&nbsp;&nbsp; JAMB TARGET</small></div><button class="button lime" data-action="capture">${icon("photo_camera")} Scan a question</button></section><section class="grid"><article class="panel"><span class="eyebrow">Rescue queue</span><h3>Highest-impact weak spots</h3><ul><li><b>Sign change during transposition</b><span>+12 marks</span></li><li><b>Indices</b><span>+8 marks</span></li><li><b>Probability</b><span>+6 marks</span></li></ul></article><article class="panel"><span class="eyebrow">How SabiCoach helps</span><h3>Not just an answer.</h3><p>We find the first wrong turn, teach the missing rule, then check if you can use it independently.</p></article></section></main>`; }
function auth(): string { const isSignup = authMode === "signup"; return `<main class="auth-layout"><section class="auth-brand"><div><strong class="brand">SabiCoach</strong><p class="eyebrow light">Nigerian exam prep, rebuilt around your mistakes.</p><h1>Every mistake has a way back.</h1><p>Build a personal rescue map for JAMB, WAEC, or NECO. Know exactly which weak spots are standing between you and your target.</p><div class="auth-proof"><b>234 <span>→</span> 280</b><small>A score goal becomes a recovery plan.</small></div></div></section><section class="auth-form"><div class="auth-card"><span class="eyebrow">${isSignup ? "Create your free account" : "Welcome back"}</span><h1>${isSignup ? "Start your Rescue Map." : "Pick up where you left off."}</h1><p class="auth-copy">${isSignup ? "No generic study plan. We start with the marks you can recover." : "Sign in to continue your personalised exam-prep plan."}</p><div class="tabs"><button class="${isSignup ? "selected" : ""}" type="button" data-auth-mode="signup">Sign up</button><button class="${!isSignup ? "selected" : ""}" type="button" data-auth-mode="login">Log in</button></div><form id="auth-form" novalidate>${isSignup ? `<label>First name<input id="name" name="displayName" autocomplete="given-name" required placeholder="e.g. Amara" /></label>` : ""}<label>Email address<input id="email" name="email" type="email" autocomplete="email" required placeholder="you@example.com" /></label><label>Password<input id="password" name="password" type="password" autocomplete="${isSignup ? "new-password" : "current-password"}" minlength="8" required placeholder="At least 8 characters" /></label><p class="form-error" id="form-error" role="alert"></p><button class="button lime wide" type="submit">${isSignup ? "Create account" : "Log in"} →</button></form>${isSignup ? `<p class="terms">By continuing, you agree to our Terms and Privacy Policy.</p>` : ""}</div></section></main>`; }
function onboarding(): string { return `<main class="shell narrow"><article class="panel onboard"><span class="eyebrow">One quick setup</span><h1>What are we preparing for?</h1><p class="lede">Choose your exam so your rescue plan uses the right question style and syllabus language.</p><div class="exam-options"><button data-exam="JAMB" class="${state.examType === "JAMB" ? "selected" : ""}"><b>JAMB</b><small>UTME · University entry</small></button><button data-exam="WAEC" class="${state.examType === "WAEC" ? "selected" : ""}"><b>WAEC</b><small>SSCE · Senior secondary</small></button><button data-exam="NECO" class="${state.examType === "NECO" ? "selected" : ""}"><b>NECO</b><small>SSCE · Senior secondary</small></button></div><div class="target-input"><label>Your target score<input id="target-score" type="number" min="1" max="400" value="${state.targetScore}" /></label><label>Latest mock score<input id="current-score" type="number" min="0" max="400" value="${state.currentScore}" /></label></div><button class="button lime" data-action="finish-onboarding">Build my Rescue Map →</button></article></main>`; }

function capture(): string { return `<main class="scanner"><section class="camera-panel"><div class="camera-frame"><video id="camera" autoplay playsinline></video><img id="preview" alt="Your selected handwritten work" ${state.imageDataUrl ? `src="${state.imageDataUrl}" class="visible"` : ""}/><div class="camera-empty" id="camera-empty">${icon("document_scanner")}<b>Use your camera or upload a photo</b><small>Keep the full question and your working inside the guides.</small></div><div class="scan-line"></div><div class="scan-box"><span>Question detected</span></div><i class="corner tl"></i><i class="corner tr"></i><i class="corner bl"></i><i class="corner br"></i></div></section><aside class="scan-side"><span class="eyebrow">Capture your handwritten solution</span><h1>Show us where you got stuck.</h1><p>Photograph a past question or your handwritten attempt. Dark ink and good daylight give the best result.</p><label class="upload" for="file">${icon("upload_file")}<b>Upload an image</b><small>JPG or PNG · max 10MB</small></label><input id="file" type="file" accept="image/*" hidden /><button class="button" data-action="camera">${icon("videocam")} Use camera</button><button class="button lime" data-action="analyse">${icon("auto_fix_high")} Find my wrong turn</button><p class="privacy">Your image is used only to analyse this attempt.</p></aside></main>`; }

function analysing(): string { return `<main class="shell center"><div class="orb">${icon("document_scanner")}</div><p class="eyebrow">SabiCoach is reading your attempt</p><h1>Tracing the step where the marks got away.</h1><p class="lede">We are separating a small procedural slip from a concept gap, then preparing the fastest repair.</p><div class="pills"><span>✓ Read question</span><span>✓ Check method</span><span>✓ Find misconception</span><span>✦ Build rescue plan</span></div></main>`; }

function diagnosis(): string { const d = state.diagnosis; return `<main class="shell">${stepper()}<section class="diagnosis"><article class="panel attempt"><span class="eyebrow">Your photographed working</span><h2>Mathematics · ${escape(d.topic)}</h2><div class="paper">Solve: &nbsp;3x − 4 = 11<br><span>3x = 11 − 4</span><br><span>x = 7 ÷ 3</span></div><small>Handwriting confidence ${Math.round(d.confidence * 100)}%</small></article><article class="panel repair"><div class="signal"><span class="eyebrow">I found the first wrong turn</span><h2>${escape(d.misconception)}</h2><p>${escape(d.diagnosis)}</p></div><h2>Let’s repair it together.</h2><ol>${d.lesson.map(step => `<li>${escape(step)}</li>`).join("")}</ol><div class="impact">${icon("trending_up")}<div><b>This pattern can cost ${d.recoverableMarks} marks.</b><small>${escape(d.teacherSignal)}</small></div></div><button class="button lime" data-action="lesson">Teach me this properly →</button></article></section></main>`; }

function lesson(): string { const d = state.diagnosis; return `<main class="shell narrow">${stepper()}<article class="panel lesson"><span class="eyebrow">Your 60-second rescue lesson</span><h1>Keep the equation balanced.</h1><p class="lede">You do not really move a number across the equals sign. You do the opposite operation to both sides.</p><section class="rule"><b>The bridge rule</b>To remove <strong>−4</strong> from the left, add <strong>+4</strong> to both sides. What you do on one side, you do on the other.</section><div class="lesson-steps">${d.lesson.map((step, index) => `<p><i>${index + 1}</i>${escape(step)}</p>`).join("")}</div><section class="memory"><b>MEMORY HOOK</b><p>Crossing the bridge changes the sign — because you must balance both banks.</p></section><button class="button lime" data-action="practice">Let me try one →</button></article></main>`; }

function practice(): string { const d = state.diagnosis; return `<main class="shell narrow">${stepper()}<article class="panel practice"><span class="eyebrow">Mastery check · 1 of 1</span><h1>Prove you own this skill.</h1><p class="lede">Solve this new question without looking back at the lesson.</p><p class="question">${escape(d.coachQuestion)}</p><div class="answers"><button data-answer="5">A. &nbsp; 5</button><button data-answer="8">B. &nbsp; 8</button><button data-answer="-8">C. &nbsp; −8</button><button data-answer="1">D. &nbsp; 1</button></div><p class="feedback" id="feedback" aria-live="polite"></p><button id="continue" class="button lime hidden" data-action="success">See my recovery →</button></article></main>`; }

function success(): string { const d = state.diagnosis; return `<main class="shell center success"><div class="star">✦</div><span class="eyebrow">Achievement unlocked</span><h1>You recovered this weak spot.</h1><p class="lede">You correctly solved a new equation. This sign-change pattern is now less likely to cost you marks again.</p><div class="recovery"><div><b>+${d.recoverableMarks}</b><small>ESTIMATED MARKS RECOVERABLE</small></div><div><b>${state.targetScore - (state.currentScore + d.recoverableMarks)}</b><small>MARKS NOW TO TARGET</small></div></div><button class="button lime" data-action="progress">View my Rescue Map →</button></main>`; }

function progress(): string { const score = state.currentScore + state.diagnosis.recoverableMarks; return `<main class="shell">${stepper()}<section class="grid progress"><article class="panel map"><span class="eyebrow">Your Rescue Map</span><h1>One weak spot, recovered.</h1><p class="lede">Your next best move is clear.</p><div class="map-space"><b class="topic done">✓ Linear equations</b><b class="topic t2">Indices · +8 marks</b><b class="topic t3">Probability · +6 marks</b><b class="topic t4">Geometry · Strong</b></div></article><article class="panel"><span class="eyebrow">JAMB score projection</span><h1>Closer than yesterday.</h1><div class="score-box"><small>CURRENT MOCK &nbsp; → &nbsp; JAMB TARGET</small><b>${score}</b><span>→</span><b>${state.targetScore}</b><small>${state.diagnosis.recoverableMarks} marks recovered from this repair</small></div><div class="mastery"><p><b>Linear equations</b><span>86% mastery</span></p><i><em style="width:86%"></em></i><p><b>Indices</b><span>42% mastery</span></p><i><em style="width:42%"></em></i></div><button class="button" data-action="capture">Rescue another question</button></article></section></main>`; }

function view(): string { switch (state.stage) { case "auth": return auth(); case "onboarding": return onboarding(); case "home": return home(); case "capture": return capture(); case "analysing": return analysing(); case "diagnosis": return diagnosis(); case "lesson": return lesson(); case "practice": return practice(); case "success": return success(); case "progress": return progress(); } }
function stopCamera(): void { cameraStream?.getTracks().forEach(track => track.stop()); cameraStream = undefined; }
function render(): void { stopCamera(); appRoot.innerHTML = `${nav()}${view()}`; window.scrollTo({ top: 0 }); bind(); }
function setStage(stage: Stage): void { state = updateStage(state, stage); render(); if (stage === "analysing") window.setTimeout(async () => { const result = await diagnoseAttempt(state.imageDataUrl); state = { ...state, diagnosis: result.diagnosis }; saveState(state); setStage("diagnosis"); }, 1800); }
async function startCamera(): Promise<void> { const video = document.querySelector<HTMLVideoElement>("#camera"); const empty = document.querySelector<HTMLElement>("#camera-empty"); if (!video || !empty) return; try { cameraStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" }, audio: false }); video.srcObject = cameraStream; empty.hidden = true; } catch { empty.innerHTML = `${icon("image")}<b>Camera permission was not available.</b><small>You can still upload an image from this device.</small>`; } }
function bind(): void { appRoot.querySelectorAll<HTMLElement>("[data-action]").forEach(button => button.addEventListener("click", () => { const action = button.dataset.action as Stage | "camera" | "finish-onboarding" | "logout"; if (action === "camera") void startCamera(); else if (action === "finish-onboarding") { const target = document.querySelector<HTMLInputElement>("#target-score")?.valueAsNumber; const current = document.querySelector<HTMLInputElement>("#current-score")?.valueAsNumber; state = { ...state, targetScore: Number.isFinite(target) ? Number(target) : 280, currentScore: Number.isFinite(current) ? Number(current) : 234, stage: "home" }; saveState(state); render(); } else if (action === "logout") { state = { ...state, authenticated: false, stage: "auth" }; saveState(state); render(); } else setStage(action); })); appRoot.querySelectorAll<HTMLButtonElement>("[data-auth-mode]").forEach(button => button.addEventListener("click", () => { authMode = button.dataset.authMode === "login" ? "login" : "signup"; render(); })); const form = document.querySelector<HTMLFormElement>("#auth-form"); form?.addEventListener("submit", event => { event.preventDefault(); void submitAuth(form); }); const input = document.querySelector<HTMLInputElement>("#file"); input?.addEventListener("change", () => { const file = input.files?.[0]; if (!file || !file.type.startsWith("image/")) return; const reader = new FileReader(); reader.onload = () => { state = { ...state, imageDataUrl: String(reader.result) }; saveState(state); render(); }; reader.readAsDataURL(file); }); appRoot.querySelectorAll<HTMLButtonElement>("[data-answer]").forEach(button => button.addEventListener("click", () => checkAnswer(button))); appRoot.querySelectorAll<HTMLButtonElement>("[data-exam]").forEach(button => button.addEventListener("click", () => { state = { ...state, examType: button.dataset.exam as RescueState["examType"] }; saveState(state); render(); })); }
async function submitAuth(form: HTMLFormElement): Promise<void> { const formData = new FormData(form); const name = String(formData.get("displayName") ?? "").trim(); const email = String(formData.get("email") ?? "").trim(); const password = String(formData.get("password") ?? ""); const error = document.querySelector<HTMLElement>("#form-error"); if (!email || !/^\\S+@\\S+\\.\\S+$/.test(email) || !password || password.length < 8 || (authMode === "signup" && !name)) { if (error) error.textContent = "Enter your name, a valid email, and a password of at least 8 characters."; return; } try { const student = await authenticate(authMode, { displayName: name, email, password }); state = { ...state, authenticated: true, displayName: student.displayName, examType: student.examType, targetScore: student.targetScore, currentScore: student.currentScore, stage: authMode === "signup" ? "onboarding" : "home" }; saveState(state); render(); } catch (reason) { if (error) error.textContent = reason instanceof ApiError ? reason.message : "We could not sign you in. Please try again."; } }
function checkAnswer(button: HTMLButtonElement): void { const feedback = document.querySelector<HTMLElement>("#feedback"); const continueButton = document.querySelector<HTMLElement>("#continue"); if (!feedback || !continueButton) return; appRoot.querySelectorAll("[data-answer]").forEach(item => item.classList.remove("selected")); button.classList.add("selected"); if (button.dataset.answer === state.diagnosis.expectedAnswer) { feedback.textContent = "Correct. You added 7 to both sides, then divided by 2. That is the balance rule in action."; feedback.className = "feedback correct"; continueButton.classList.remove("hidden"); state = { ...state, masteryVerified: true }; saveState(state); } else { feedback.textContent = "Close. Remove −7 by adding 7 to both sides first, then divide by 2."; feedback.className = "feedback retry"; continueButton.classList.add("hidden"); } }
render();
